"""add user to invoice.

Revision ID: 18335740a585
Revises: ca2552a15d23
Create Date: 2025-08-24 14:44:34.732496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18335740a585'
down_revision: Union[str, None] = 'ca2552a15d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'user_uid')
    # ### end Alembic commands ###
