"""added default status to tables.

Revision ID: 28dfc8f7a7d6
Revises: 1df69bca0ced
Create Date: 2025-08-19 11:03:31.528507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28dfc8f7a7d6"
down_revision: Union[str, None] = "1df69bca0ced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "services", "status", existing_type=sa.VARCHAR(), nullable=True, server_default="ACTIVE"
    )  # Add this
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "services", "status", existing_type=sa.VARCHAR(), nullable=False, server_default=None
    )  # Remove the default
    # ### end Alembic commands ###
