"""add computed column in budget table

Revision ID: 390edabbba2a
Revises: e7ddde29e6e9
Create Date: 2025-09-04 11:41:15.436468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390edabbba2a'
down_revision: Union[str, None] = 'e7ddde29e6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'amount_remaining')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('amount_remaining', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
