"""make expenses table note column optional.

Revision ID: 3f27b9acbb32
Revises: 9b8f12e9a487
Create Date: 2025-08-24 08:44:18.491476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f27b9acbb32"
down_revision: Union[str, None] = "9b8f12e9a487"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("expenses", "note", existing_type=sa.VARCHAR(), server_default="", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("expenses", "note", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
