"""add other_name column in patient table.

Revision ID: 3fb27a5d98e3
Revises: d67490c221b9
Create Date: 2025-08-25 09:08:36.986842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = "3fb27a5d98e3"
down_revision: Union[str, None] = "d67490c221b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("other_name", AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "other_name")
    # ### end Alembic commands ###
