"""created abstract invoice table

Revision ID: 438ff77c9ff8
Revises: e30ea589f03e
Create Date: 2025-09-04 12:14:04.833241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438ff77c9ff8'
down_revision: Union[str, None] = 'e30ea589f03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'net_amount_due')
    op.drop_column('invoices', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('net_amount_due', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
