"""adjust duplicate foreign key relationship for user table revised

Revision ID: 4641d21fb645
Revises: 8b56cafd09cd
Create Date: 2025-08-19 13:26:42.843082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4641d21fb645'
down_revision: Union[str, None] = '8b56cafd09cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
