"""make serio_no nullable

Revision ID: 46d213ee04c9
Revises: e705a713fec1
Create Date: 2025-08-22 10:10:32.947752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d213ee04c9'
down_revision: Union[str, None] = 'e705a713fec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('budgets', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('expenses', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expenses', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('budgets', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bills', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
