"""add default status value to department table

Revision ID: 54e84842cee3
Revises: cc369b744c10
Create Date: 2025-08-19 22:41:28.635030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54e84842cee3"
down_revision: Union[str, None] = "cc369b744c10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "status", existing_type=sa.VARCHAR(), server_default="ACTIVE", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
