"""add properties to invoice and payment tables

Revision ID: 598dfa96981d
Revises: 3fb27a5d98e3
Create Date: 2025-08-25 10:55:12.837295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = "598dfa96981d"
down_revision: Union[str, None] = "3fb27a5d98e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("title", AutoString(), nullable=False))
    op.add_column("invoices", sa.Column("tax_percent", sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column("invoices", sa.Column("discount_percent", sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column("invoices", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("invoices", "name")
    op.drop_column("invoices", "tax_amount")
    op.alter_column("payments", "invoice_uid", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("payments_invoice_uid_fkey"), "payments", type_="foreignkey")
    op.create_foreign_key(None, "payments", "invoices", ["invoice_uid"], ["uid"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.create_foreign_key(op.f("payments_invoice_uid_fkey"), "payments", "invoices", ["invoice_uid"], ["uid"])
    op.alter_column("payments", "invoice_uid", existing_type=sa.UUID(), nullable=False)
    op.add_column(
        "invoices", sa.Column("tax_amount", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True)
    )
    op.add_column("invoices", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column("invoices", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("invoices", "discount_percent")
    op.drop_column("invoices", "tax_percent")
    op.drop_column("invoices", "title")
    # ### end Alembic commands ###
