"""add default status and availabilty to budgets table.

Revision ID: 6490ae0e34ff
Revises: 3b268b1c6b04
Create Date: 2025-08-20 16:04:12.487801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6490ae0e34ff"
down_revision: Union[str, None] = "3b268b1c6b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("budgets", "status", existing_type=sa.VARCHAR(), nullable=True, server_default="PENDING")
    op.alter_column("budgets", "availability", existing_type=sa.VARCHAR(), nullable=True, server_default="AVAILABLE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("budgets", "status", existing_type=sa.VARCHAR(), nullable=False, server_default=None)
    op.alter_column("budgets", "availability", existing_type=sa.VARCHAR(), nullable=False, server_default=None)
    # ### end Alembic commands ###
