"""adjust duplicate foreign key relationship for user table

Revision ID: 8b56cafd09cd
Revises: dfd4bb33764d
Create Date: 2025-08-19 13:24:14.665836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b56cafd09cd'
down_revision: Union[str, None] = 'dfd4bb33764d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
