"""add budget assignee_uid

Revision ID: 9b8f12e9a487
Revises: 46d213ee04c9
Create Date: 2025-08-22 11:10:18.327162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8f12e9a487'
down_revision: Union[str, None] = '46d213ee04c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('assignee_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'budgets', 'users', ['assignee_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'assignee_uid')
    # ### end Alembic commands ###
