"""add patient_type column to patient table.

Revision ID: 9ce0369d99d6
Revises: a8aa1a72bdcd
Create Date: 2025-08-25 06:38:43.316684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = "9ce0369d99d6"
down_revision: Union[str, None] = "a8aa1a72bdcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("patient_type", AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "patient_type")
    # ### end Alembic commands ###
