"""adondelete cascade

Revision ID: a8aa1a72bdcd
Revises: 6958e6c30812
Create Date: 2025-08-24 20:03:28.456736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8aa1a72bdcd'
down_revision: Union[str, None] = '6958e6c30812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_budget_uid_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'budgets', ['budget_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_budget_uid_fkey'), 'expenses', 'budgets', ['budget_uid'], ['uid'])
    # ### end Alembic commands ###
