"""remove column in payments table

Revision ID: d208f220f0b6
Revises: 598dfa96981d
Create Date: 2025-08-25 12:15:17.368670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "d208f220f0b6"
down_revision: Union[str, None] = "598dfa96981d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("note", AutoString(), nullable=False))
    op.drop_column("payments", "received_at")
    op.drop_column("payments", "Note")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("Note", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column(
        "payments", sa.Column("received_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.drop_column("payments", "note")
    # ### end Alembic commands ###
