"""add user_uid column in patient table.

Revision ID: d67490c221b9
Revises: 9ce0369d99d6
Create Date: 2025-08-25 06:45:11.294101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67490c221b9'
down_revision: Union[str, None] = '9ce0369d99d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_uid')
    # ### end Alembic commands ###
