"""adjust duplicate foreign key relationship for budget table

Revision ID: dfd4bb33764d
Revises: 28dfc8f7a7d6
Create Date: 2025-08-19 13:21:41.093890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd4bb33764d'
down_revision: Union[str, None] = '28dfc8f7a7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
