"""set staff_no as optional

Revision ID: e705a713fec1
Revises: 6490ae0e34ff
Create Date: 2025-08-20 22:24:02.744477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e705a713fec1'
down_revision: Union[str, None] = '6490ae0e34ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'AVAILABLE'::character varying"))
    op.alter_column('users', 'staff_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'staff_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('budgets', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'AVAILABLE'::character varying"))
    # ### end Alembic commands ###
