"""column revision for invoice table.

Revision ID: edab1e7387fd
Revises: d208f220f0b6
Create Date: 2025-08-26 07:39:36.535656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edab1e7387fd'
down_revision: Union[str, None] = 'd208f220f0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'service_uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoices', 'department_uid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'department_uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoices', 'service_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
